### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by ed-sharp** [asu-cis-capstone/heroes#18]
![mock up 01](https://cloud.githubusercontent.com/assets/10728958/6281801/347090b0-b885-11e4-871f-beb2e578fb31.png)
![colored version](https://cloud.githubusercontent.com/assets/10728958/6281803/3b1cbb50-b885-11e4-85f7-45111e203b84.jpg)
![heroesforstudents-text3-logo-cmyk](https://cloud.githubusercontent.com/assets/10728958/6281804/4002459a-b885-11e4-9f18-ed28297cf0f3.jpeg)

**Comment by charlesbrown3014** [comment]
Looks great Edward!  I like this a lot. You implemented the side spacing
also so that looks awesome.  I think we can submit both versions of the
site and see which one Chris likes better.  I like what Arick and I worked
on and it looks great but I like Edward's just as much if not more.  I
think we should leave the decision up to the client. He may want to pick
and choose things from one or the other or simply go with one of the other
as is.  Here is what Arick and I have:

[image: Inline image 1]

William could your present these to Chris and see how he wants to proceed?
Great job everyone.  Please post the code you worked on in github.  After
Chris makes a decision we are going to post that code up in the test bay
and work off a copy of it on github so we can work more efficiently and not
repeat work. This was great that we were able to come up with different
ideas for the site design.  Everyone have a great weekend!

Charles

**Comment by ed-sharp** [comment]
I think we should implement a little bit of both designs. I am thinking we could take out the borders and use the bright colors like Arick's design. But have the left and right margins like in my design. I am trying to figure out a way to put buttons in the slideshow that change as the picture changes.

**Comment by charlesbrown3014** [comment]
Here is the hybrid from Arick and I. I added the margin (like Edward) on
the sides and changed the menu color to a darker color for contrast with
the margin and the slideshow but kept Arick's lightblue buttons since it is
over the slideshow.  I also changed the footer a bit and used one of the
colors that Chris gave us to line the bottom of the page. I think mixing
the two is a good idea.  Let's see what you come up with Edward. Arick you
can play around with it also and I think I may do the same. With us coming
up with creative ideas we will give Chris good options to choose from.  I
would like to get a solid design for the website no later than Sunday
night.  That way we can start on functionality and testing.  I already
showed the site to a few random people to get their opinion.  That is the
reason I went with the dark blue for the Top bar.  Great work everyone!
Let's keep it moving!!

**Comment by williamsugihara** [comment]
Do you want me to show it to anybody yet?  is the code on the .info site?

**Comment by charlesbrown3014** [comment]
Please go ahead and show Chris the two pages.  We will still go ahead and
blend them together in a couple of different ways. I think Edward should
work on his changes to the site and if Arick as ideas that he do the same.
I will do the same also. We can post our code in the repository for access
to all if they have any creative ideas for the home page.  I haven't put
the code on the '.info' site yet.  I want to get a page agreed upon before
putting up the code. From that page we can change it around slightly or add
buttons, features, pages and links.  That way we have a good initial
template for us all to test on.  That code for the initial page will be on
github for us all to work on so that way any changes we make to code can be
observed by everyone and we can also divide up tasks more efficiently.
Right now we are in a design phase of the project so everyone's ideas and
efforts are into creating a good looking website. You are working on the
animation (which is a huge milestone), Arick, Edward and I are all
creatively sharing ideas and trying to peg down a good look for the
client.  That is why I think Sunday is a good deadline to have something
solid decided on.

**Comment by ArickHanna** [comment]
That sounds great guys! I will definitely mess around with the site this
weekend so we can have something by Sunday.

**Comment by charlesbrown3014** [comment]
Here is a quick tutorial on how to use Github for Windows.  It's quick and
dirty and only about 6 or 7 minutes.

https://www.youtube.com/watch?v=LufnCoPShZE

**Comment by charlesbrown3014** [comment]
Just to verify (in case you haven't already done it), once you download
Github for Windows on your computer you will then open the program using
the white circle with the cat's shadow icon and when the window pops up you
should already have the 'Heroes-codiing' repository available.  Click the
plus sign above it on the left side of the window and select
'asu-cis-capstone' and a list of repositories will appear.  Select the
'heroes' repository and then make a clone somewhere convenient on your
computer (I did like the tutorial said and put it on my Desktop) and that
folder should be named 'heroes.'

All things you put in this folder will be shared with the group so we can
make alterations. Please input your webpage code in here with your name on
the folder and specify that it is for the home page in the folder name.
Example: Charles_home (would contain html and css code for the home page I
worked on.

I am going to sync the code I have up right now so everyone will have
access.  Everyone please do the same when you get the opportunity.
